
services:
  - type: web
    name: performance-dashboard-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    autoDeploy: true
