services:
  - type: web
    name: performance-dashboard
    env: python
    buildCommand: pip install --prefer-binary -r requirements.txt

    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12

